# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setFileName.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class setFileNameWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Set File Name")
        Form.resize(600, 100)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 27, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 27, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 27, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        Form.setFont(font)
        self.FileNameLabel = QtWidgets.QLabel(Form)
        self.FileNameLabel.setGeometry(QtCore.QRect(20, 30, 85, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.FileNameLabel.setFont(font)
        self.FileNameLabel.setStyleSheet("color: rgba(217, 217, 217, 1)")
        self.FileNameLabel.setObjectName("FileNameLabel")
        self.FileName = QtWidgets.QLineEdit(Form)
        self.FileName.setGeometry(QtCore.QRect(120, 28, 450, 25))
        self.FileName.setStyleSheet("border-radius: 5px;\n"
"background-color: #4E5058;\n"
"color: rgba(217, 217, 217, 1); ")
        self.FileName.setObjectName("FileName")
        self.ConfirmBtn = QtWidgets.QPushButton(Form)
        self.ConfirmBtn.setGeometry(QtCore.QRect(480, 62, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.ConfirmBtn.setFont(font)
        self.ConfirmBtn.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #4E5058;\n"
"    color: rgba(217, 217, 217, 1); \n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgba(40, 76, 184, 0.4);\n"
"}")
        self.ConfirmBtn.setObjectName("ConfirmBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Set File Name", "Set File Name"))
        self.FileNameLabel.setText(_translate("Set File Name", "File Name"))
        self.ConfirmBtn.setText(_translate("Set File Name", "Confirm"))
        self.ConfirmBtn.setShortcut(_translate("Set File Name", "Return"))